dist: trusty
language: node_js
node_js:
- '8'
- '10'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm run lint
- npm test
before_deploy:
- npm run prepublishOnly
deploy:
  provider: npm
  email: mooyoul@gmail.com
  skip_cleanup: true
  api_key:
    secure: C56CEKPxJgSD4lrwcMUCgzZJWeYdV4kTSXYEi6HzmbAQwUhVkii4MARC+/FQzZPz8R7GhHBe89jWDb+CnAeB8sXw5ctUOeOuOoLT0mC9d17+Y2WpXHXP8a/mv2HnrD9CC9fQoqrrnaDCMPr1pIicrWfip5R2v0IoxtAkH6tiYB/FcEq/dsRvMnEZhVbBetMPhH3n//DMuIdslL4D7kHySJMojyHjEX9q5Cq8nlaj68rCdiD3ZppSYJA064Y8vLODxPZNHoj83NvkZ69CvFUcWJSPoPU3MD/ekFhMXxTN/UyAhTceTq9v8LKFx3Uly+3eJMmFdseAanO3wLcilHUvHm+RjjYeNItt7fpcKzSe7hJ7en0S2jDv2EPUiZaUe/xcSW3oriC53moNANeEaX4YH6vP7tcu8ojk6scm/pSbHgBcLtD2oKLQR2hS4T50Zo1+J16VVv+t3a6FYFwrt2ZBCbjcLG8v7BQlbbCLcan+ZBV3R9aes6rd6t6bWg5bgJEOPcLoGPazNHozoTDOautzqOOQXMHP1h+dD9pzVjlEueMm3tsm0ibWHHP1NWJv1xXq69VhfAB3M4sOiE9e3RUFuMeq/cBBOZH6iXF8Uhdt2Q2O89SiQer4J3DSbNv/nDF+27o6IgsuAIjzjEBSCXpNLfa7YzOTjdjF5xEaiVz6ILQ=
  on:
    tags: true
    repo: mooyoul/get-orientation
