dist: trusty
language: node_js
node_js:
- '8'
- '10'
script:
- npm run lint
- npm test
before_deploy:
- npm run prepublishOnly
deploy:
  provider: npm
  email: mooyoul@gmail.com
  skip_cleanup: true
  api_key:
    secure: eUDA3Um7ABvKpNqWDLOj3qjRY9FOutK1WkbqoNNJe2x8cQ5zKdEMPeWawvYA+7EKIOuG93ynXnqmXhFiHQmbA1uTz1TNCK5ZHJ4IqeEhw+zzG5Io+CbZXsmejk0isZVBRPmKGkmE0AEd02aDph8u6LTPZnkJbbzhI8d2hCBwxpY86CBTAVCbxAAVuQBpR4/7cRorw+FaEViwrQM1HiIGTMBUAi+V9YrV0BEqn/uyDIySPn28ble5ke64S72LfHfZDEyFoxR+MPxgjSaAfzrGXx2dg4UeFDZaf3g7ybau+26PFR05dOcc7NasmtY4dCsmUHwk5xG44fnjo2Qqepu4jVPH9T76SPtxfX425yO0J/vkW4qDn5usdl3wgNAGCaq6f5ht4NGLlsxrr3xw4CLW1g0a4LHS9xA3m99wR2/E+9tYUO2Y/yTZYcm7vUeWF3CKV3n5st/NQ7fT23kTfcLI+0nLc9h9QTfansqq37ozoVNyM58v1sRINYojTCzdSeI8HpOykAPYGl2JOIDP3Ziax1HgDPQ++V77NQ9TFDn2kg8xc51r2nhv7KqmiaLenTlRgcWEAAJPojJZz7CtPlvl+Eq3PVGzOZhApFRLYeaHn/PqfTuiZjwC5kERdEELyGezLK32qeOKXvpnKoOtDivkkWCVfyAso9if66guaFFsIU4=
  on:
    tags: true
    repo: mooyoul/get-image-orientation
