dist: trusty
language: node_js
node_js:
- lts/*
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
install:
- curl -o browserstack-local.zip https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip browserstack-local.zip
- npm ci
stages:
  - name: Test
  - name: Publish
    if: branch == master && repo == 'mooyoul/get-orientation'
jobs:
  include:
    - stage: Test
      name: Lint
      script: npm run lint
    - stage: Test
      name: Unit Test
      script: npm test
    - stage: Test
      name: E2E Test
      node_js: lts/carbon
      env:
        - secure: Ffzl0wHmps3udkFCKreTuB+KyHbiSvD1NwcpdauluqwHkdrki4N6GwDtJ0++IIeNtjMyaMQ0o5EfQ4A2Iyals2FQP5fM0JU+h9LUEmgN9IpsyhgZ1NTapPjk00XsaqCH3MwxaZkyBn36R3J2vaaHeDkhHyabbrSRXrwITr3H6Fl2JEDmOlyyERDcrbvJoiTMrJUHB/B70jSvymmk0qiCel0oHqC/fXh7PlBkrVDloR6i24gvYV3kMOqhJbtC0lU/5zPDiiSod4386xpb/Pdla5xtlYHy0/Oma8cZ2h/iilKW+A2DivgINX+rzmdJy2rYvE6e5aCTOLnHydlpWlYuyDWh+x6LqOdamoQ/R8m+sAxm9vt+PxZadcBrwvCkDHCPu/1vGk7xnB5sB29ab1bXVatsrI98iWe43m4eCUC8uG/s/0BL1Z0MyyeaO6BSoe5Lfstn6MMCqA2B/LNm9sB0zeNn53gnVbOzbj68pe1BjfOmPg4bS2V7jfgK9TYZPUr9iHmCXMs+OA1VR2QN6+DjXOmMAnOblKGZLSK5sH2pBC4n12I9+3tK3vyYOXkj9sNiaJTwdyjtQH8J4xgEDydtjSqkT/IhKWok7k44TedXzqvZo6jERsFaAPF3mvUmo9OiwkdbeGgo3S3W3zzc3cu9aXo8VhJfgw0Az1oFl9/N1vk=
        - secure: moejyOCLli3khkrUAnzEj+aZedzP74SToTTMte2yPrMsRgr0kcSAIGR7pPqfgYg7pVY0KbB4+EdCemSKHL6hV8FYbRvd/Nw+lP3lj4rCV1ypr6kS6AGaCNu8os8tRehDjHDxIh+3tzaD31a/zlKzf0LcqNwqFUI//CfBliv51BBdjp7meXyO2x5KPkdpcEku5inCnloanb1KyzvBP/nMDGECqK+U2XIExODGo0SkpHMjDOlD0+fTD9rYaDHjoCAWj09zZSHpaeeQ2HUoSX7kDKjfejOSx1DA5kCdSIBQpDHcOi03nQkgwDY+5E2Azb8AhUXFlFA8ofVwEkqy0xIFmS1JFv2PhORT/ijh1IJ4K7OF0nXjqERwopwm+AYlnz6837SQicH0HFCXinjKmA5XylfgISLoqr5n7D8VSgrMFhW0wwprrVfsE+8DjTOKmpRRuM6giYz4AtVbBnvuZAk/9AOqCDzIz/2Ca4FXHFleNXpQaUp7rGjLZTtMyF34kmeq3dnzxROEgR/PXzqYOrvjtc1q4OIopOpKrlXLeK3uxDcAgJr9Z8Gr1QhZyhodcfWi7DU21SdrSYaiFz9A81CzRQPAdjMA4KHyQiFuAhs+PDdxceiAStLbQUfHqjbQ+JEKsUnMzNLfDKMAiphajWmAwmQJHX3bh2SOqnrneIOFUtk=
      script: |
        ./BrowserStackLocal -k $BROWSERSTACK_ACCESS_KEY &
        echo $! > $TMPDIR/bs-local.pid
        npx -p node-static static . --port=8080 > /dev/null &
        echo $! > $TMPDIR/node-static.pid
        sleep 10
        npm run pretest
        npm run test:browserstack
        npm run posttest
        test -e $TMPDIR/bs-local.pid && pkill -SIGINT -P $(cat $TMPDIR/bs-local.pid)
        test -e $TMPDIR/node-static.pid && pkill -SIGINT -P $(cat $TMPDIR/node-static.pid)
        rm -f $TMPDIR/bs-local.pid $TMPDIR/node-static.pid
    - stage: Publish
      node_js: lts/carbon
      env:
        - secure: CLNMcJuzb7NkQsLojabevmWZGMXOrVxl4FTGtpjw4h76BFIPlAw6YuchxHcmJbWkJ2ccaYJn1I2Gmc+iFWuSQ5cdte54WALIZnjHRgsKATTiVu0dZ4+bmMx76AvyU6z7DUqAVxaZw+RDsUsAQv7i3SYksfQ/JjIcTAq7WgXob9MiPh1g9ppOF24hSsLVbYH6cqvGpm/KwO0Avt6K1OOJTBVyCNTnhJKXA1msKVGGL9i265kE1W7IRVghTS6DhsBbaRUfpGVnttj6ibfFtgZY/0XIrAxFgfe9fY8goBjuTfcOa6Hv2qTZsOSCbSFuC+TptPbsLCsqOC8pAMmiTz+pB+SpotvgLnJEVt0Zl4oxdn63i4PufQyHHiGf/UaPBPfyTk+iExg2bHnsJoYBvSkrZFAqSnxFW4OuvgTuGE2skIPNOeSEK3AlW6RrjboIqpE4F6zm5/bFaG/86nKpoqViwqv7aJyLjjolhwzFAxg+gY3jJLVg7uWeMbkOyZjoYz138Si1LkCq+AfqRxL+zyDiPlOyqdd99CH30T4AJah6yn6wJ0EPugTRstV4bvfhgba76cbX7DsfMXR8cnECZL38xaBArT6E7s0/4RsYwc2y5L4Yy7WfBAErE7EmWQKlNx8mTzQ6TROroMJcNGs9dt4zMDJlX4OJVVMagq8S6Ey3nqI=
        - secure: E3ANxCmXhRY1NTHw5XSGaHtg97XzRw2/htqQLftE0GWky9kLYpW0dJQpostXfnGBiwKN2a3HuAeUStmxNAEULKks8EcleVW+3Zx+qLmSLtnX98fEv7IxctSVpDhhH85DQ05kwmdKnmqAahwQ412SsQn3URT7cLrNvxzt/L4Q3JotsmKXvs0TD/Iv1vFJQbprYabZ7+0qslo1d+dnxdCtk0lYJREyB559IKq2/d14YskZtdY6XDvR2PnoG7lhY4rF26AL31CzCJZfxVWOqtzJxizggWlK7vbZnPYt1XUAwWyFvKGIm2JUZ6586gWqcBMErRx0cvVZ/w3uszRj8xjVyVaiFzcj1brgWIiRSJCIHb7B49OP1lM4B7EK0nXqhP6cPnhYAJshpkusQoTikU5HpQWKIKSIBdN+KdUEXAgGpnQJGOq6mfR0vs7RtK2h5VPZaXA0nvGWg7XyjqX/WAqgluH8vsB84JAI6I94JgN+G//arzdS1Px1o2QynSPBW4C8yL0NR/qqLKtsj2kdU/pajTFDC4R/S8Mk6k5nnX+7efHPdZNk7S32AS5g/KTQ0K5jnKIj0dhFAXLS1B4CZxhPZ5ODhejAQ13SJ+DFtoJkGekXZPCzJBClufiyPYpqNhZir8B8FbVDef5F02l1Lnzow2OzVCY0OJdpMtMKVGsV0qQ=
      script: npx semantic-release
